# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: TwitterBot

on:
    # Scheduling is meant to optimize views
    schedule:
      # Runs every 20 minutes from 7am to 2am Sunday to Thursday (EST)
      - cron: '0,20,40 0-5,12-23 * * 0-4'
      # Runs every 20 mins on Friday b/w 7am and 11am Friday (EST)
      - cron: '0,20,40 12-16 * * 5'

jobs:
  run-twitter-bot:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python3 twitter_bot.py