# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: TwitterBot

on:
    # Scheduling is meant to optimize views
    schedule:
      # Runs every 30 minutes from 7am to 11pm Sunday to Thursday
      - cron: '0,30 7-22 * * 0-4'
      # Runs every 30 minutes from 7am to 6pm on Friday
      - cron: '0,30 7-17 * * 5'

jobs:
  run-twitter-bot:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python3 twitter_bot.py